# Generated by Django 3.0.8 on 2020-07-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_Unit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
